### ISSUE TITLE
11.3 is not supported?

### ISSUE THREAD

**Issue by oovz** [TiniVi/safehax#17]
not supported kernel version

**Comment by TheProgrammerEX** [comment]
Yep that's right. Because 11.3 doesn't have a way to get arm11 access and they have updated their safeferm you can't run safehax on 11.3.

**Comment by TiniVi** [comment]
https://3dbrew.org/wiki/Title_list#00040138_-_System_Firmware
https://yls8.mtheall.com/ninupdates/titlelist.php?date=02-06-17_07-00-47&sys=ktr
https://yls8.mtheall.com/ninupdates/titlelist.php?date=02-06-17_07-00-38&sys=ctr

Safehax itself shouldn't need any tweaks to work on 11.3 (Since, as far as I can tell, SAFE_MODE has not been updated), all that would be required is an ARM11 exploit on 11.3 to be run before-hand. Correct me if I'm wrong.

**Comment by CrimsonMaple** [comment]
"The firmlaunch function panics when attempting to launch SAFE_FIRM(New3DS programID-low bitmask is masked out) if that flag has been set, to prevent safefirmhax." - 3dbrew 

Curse you hard coded flags set on boot.

**Comment by lordsba** [comment]
sighax the next expoit will be able to downgrade 11.3 ti hack

**Comment by TiniVi** [comment]
o rip safehax then (maybe :>)

**Comment by TiniVi** [comment]
Gonna close this for now, since this isn't technically an issue with safehax.
